### ISSUE TITLE
Packages missing

### ISSUE THREAD

**Issue by Hugo-Contreras** [ciena-frost/ember-frost-ecosystem#10]
When installing for the first time two modules are missing so the installation doesn't work properly. We have to install it manually with NPM and then relaunch the installation of ember-frost-ecosystem. The two module are :
- figures
- chalk

Configuration :
- MacOS 10.11.6
- Node.js 6.10.1
- NPM 3.10.10
- Ember CLI 2.8.0

**Comment by dafortin** [comment]
Fixed in https://github.com/ciena-blueplanet/ember-cli-ecosystem-installer/pull/82
